redis:
  persistence:
    enabled: false

config:
  logLevel: "DEBUG"
  internalDatabase: true
  updateSchema: false
#  github:
#    clientId: "97c64904c68b2737fdca"

  oidc:
    clientId: gfdev2
    audience: "gfdev2"
    loginUrl: "https://gf-kc.lsst.ac.uk:8443/realms/testing/protocol/openid-connect/auth"
    tokenUrl: "https://gf-kc.lsst.ac.uk:8443/realms/testing/protocol/openid-connect/token"
    issuer: "https://gf-kc.lsst.ac.uk:8443/realms/testing"
    scopes:
      - "openid"
    usernameClaim: "preferred_username"

  ldap:
    url: ldap://gf-kc.lsst.ac.uk
    groupBaseDn: ou=groups,dc=lsst,dc=ac,dc=uk
    groupObjectClass: posixGroup
    groupMemberAttr: memberUid
    groupSearchByDn: false
    userBaseDn: cn=users,dc=lsst,dc=ac,dc=uk
    userSearchAttr: uid
    addUserGroup: false
    uidAttr: uidNumber
    gidAttr: gidNumber
    nameAttr: gecos

  groupMapping:
    "admin:token":
      - "lsst"
    "admin:jupyterlab":
      - "lsst"
    "exec:admin":
      - "lsst"
    "exec:internal-tools":
      - "lsst"
    "exec:notebook":
      - "lsst"
    "exec:portal":
      - "lsst"
    "read:image":
      - "lsst"
    "read:tap":
      - "lsst"
    "write:files":
      - "lsst"
    "user:token":
      - "lsst"
