redis:
  persistence:
    enabled: false

config:
  internalDatabase: true
  updateSchema: false

#  github:
#    clientId: "97c64904c68b2737fdca"

  oidc:
    clientId: gfdev2
    audience: "gfdev2"
    loginUrl: "https://gf-kc.lsst.ac.uk:8443/realms/testing/protocol/openid-connect/auth"
    tokenUrl: "https://gf-kc.lsst.ac.uk:8443/realms/testing/protocol/openid-connect/token"
    issuer: "https://gf-kc.lsst.ac.uk:8443/realms/testing"
    scopes:
      - "openid"
      - "email"
      - "groups"
      - "profile"
    usernameClaim: "name"

  # Allow access by GitHub team.
  groupMapping:
    "exec:admin":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:internal-tools":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:notebook":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:portal":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:image":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:tap":
      - github:
          organization: "lsp-uk"
          team: "dev"

  initialAdmins:
    - "gpfrancis"
