redis:
  persistence:
    enabled: false

config:
  internalDatabase: true
  updateSchema: true

  github:
    clientId: "97c64904c68b2737fdca"

  # Allow access by GitHub team.
  groupMapping:
    "exec:admin":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:internal-tools":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:notebook":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "exec:portal":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:image":
      - github:
          organization: "lsp-uk"
          team: "dev"
    "read:tap":
      - github:
          organization: "lsp-uk"
          team: "dev"

  initialAdmins:
    - "gpfrancis"
